### ISSUE TITLE
Download Failure

### ISSUE THREAD

**Issue by Dumpshock** [WesternGamer/NoLogging#1]
Plugin fails to download from Github archive on game load.  
Appears the file it's attempting to pull either doesn't exist or isn't available publicly.

``
2021-11-12 21:12:21.960 - Thread:   1 ->  [PluginLoader] Downloading https://github.com/WesternGamer/NoLogging/archive/3e1845cc7e1f762b182aafb973fcc3d2dda1bd19.zip
2021-11-12 21:12:22.270 - Thread:   1 ->  [PluginLoader] Failed to load WesternGamer/NoLogging|No Logging because of an error: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at avaness.PluginLoader.Network.GitHub.DownloadRepo(String name, String commit, String& fileName)
   at avaness.PluginLoader.Data.GitHubPlugin.CompileFromSource(Action`1 callback)
   at avaness.PluginLoader.Data.GitHubPlugin.GetAssembly()
   at avaness.PluginLoader.Data.PluginData.TryLoadAssembly(Assembly& a)
2021-11-12 21:12:28.745 - Thread:   1 ->  [PluginLoader] Finished startup. Took 8749ms
``

**Comment by WesternSpace** [comment]
This should now be fixed soon.
